# This is a basic workflow to help you get started with Actions

name: Create .env file

# Controls when the action will run. 
  # Triggers the workflow on push or pull request events but only for the main branch
on:   
   push:
    branches: [ main ]
   pull_request:
     branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      working-directory: ./
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v1
    - name: read-json
      env:
        foo: ${{ secrets.FOO }}
    - name: create-json
      uses: actions/checkout@v2
      with:
        name: "env.json"
        foo: ${{ secrets.FOO }}
        dir: "/"
    - name: print-env
      run: |
        cat 'env.json'
      working-directory: ${{ env.working-directory }}
    - name: print-json
      run: |
        cat 'README.md'
      working-directory: ${{ env.working-directory }}
