# This is a basic workflow to help you get started with Actions

name: Create .env file

# Controls when the action will run. 
  # Triggers the workflow on push or pull request events but only for the main branch
on:   
   push:
    branches: [ main ]
   pull_request:
     branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
# jobs:
#   create_env_file:
#     runs-on: ubuntu-latest
#     steps:
#       - name: create-json
#         id: create-json
#         uses: actions/checkout@v1
#         with:
#           foo: ${{ secrets.FOO }}
#           downloaded_filename: 'env.json'

jobs:
  run:
    name: Add a text file
    runs-on: ubuntu-latest

    steps:
      # If you need to, you can check out your repo to a different location
      - uses: actions/checkout@v2
        with:
          path: './'

      # You can make whatever type of change to the repo...
      - run: echo ${{ secrets.FOO }} > ./.env

      # ...and then use the action as you would normally do, but providing the path to the repo
      - uses: EndBug/add-and-commit@v7
        with:
          message: 'Add the very useful env file'
          add: '.env --force'
          cwd: './'
